version: 4
shared:
  environment:
    PACKAGE_DIRECTORY: redislite

jobs:
  validate_test:
    template: python/validate_unittest
    requires: [~commit, ~pr]

  validate_lint:
    template: python/validate_lint
    requires: [~commit, ~pr]

  validate_codestyle:
    template: python/validate_codestyle
    requires: [~commit, ~pr]

  validate_documentation:
    template: python/documentation
    environment:
      DOCUMENTATION_PUBLISH: False
    requires: [~pr]
  
  package_build_manylinux2014:
    template: python/package_python
    image: manylinux2014
    environment:
      PUBLISH: False
    requires: [~pr]
    
  generate_version:
    template: python/generate_version
    requires: [~commit]

  publish_test_pypi:
    template: python/package_python
    environment:
      PACKAGE_TAG: False
      PUBLISH: True
      TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    requires: [validate_test, validate_lint, validate_codestyle, generate_version]

  verify_test_package:
    template: python/validate_pypi_package
    environment:
        PYPI_INDEX_URL: https://test.pypi.org/simple
    requires: [publish_test_pypi]

  publish_documentation:
    template: python/documentation
    requires: [verify_test_package]

  publish_pypi:
    template: python/package_python
    environment:
      PUBLISH: True
    requires: [verify_test_package]
