#!/bin/bash
export MACOSX_DEPLOYMENT_TARGET="10.6"
export PYTHON_CONFIGURE_OPTS="--enable-universalsdk=/ --with-universal-archs=intel"

python setup.py sdist upload
python2.7 setup.py bdist_wheel upload
python3.4 setup.py bdist_wheel upload
python3.5 setup.py bdist_wheel upload
